In [1]:
import numpy as np

## vectors


In [2]:
vect_a=np.array([1,2,3])
print(type(vect_a))
print(vect_a.shape)
print(vect_a.ndim)
print(vect_a.size)

<class 'numpy.ndarray'>
(3,)
1
3


## matrices

In [3]:
#rank2 or 2d array
mat_a=np.array([[1,2,3],[4,5,6]])
print(mat_a)

[[1 2 3]
 [4 5 6]]


In [4]:
#rank3 or 3d array
mat_b=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(mat_b)
print(mat_b.ndim)
print()

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
3



In [5]:
#accessing elements in a matrix
mat_b=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
print(mat_b[0,1,1])
mat_b[1,0,1]==6

4


True

In [6]:
#taking the transpose of a matrix
mat_b=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
np.transpose(mat_b)

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

In [7]:
#transpose of a matrix
mat_b=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
np.transpose(mat_b)

array([[[ 1,  5,  9],
        [ 3,  7, 11]],

       [[ 2,  6, 10],
        [ 4,  8, 12]]])

## In-built arrays

In [8]:
#all zeroes as the elements
zeros=np.zeros((4,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
#array containing all ones
ones=np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
#a specified number
spec=np.full((2,3),6)
spec

array([[6, 6, 6],
       [6, 6, 6]])

In [11]:
#random elements b2n 0.0 and 1.0
random=np.random.rand(2,4)
random

array([[0.45265604, 0.90210012, 0.54720893, 0.12280703],
       [0.18970131, 0.12479909, 0.2424149 , 0.07140269]])

In [12]:
#random integers with the specified highest number
randint=np.random.randint(10,size=(3,4))
randint

array([[7, 1, 4, 2],
       [3, 9, 4, 3],
       [9, 2, 2, 4]])

In [13]:
#identity matrix
id_1=np.eye(3,4)
id_1
id_2=np.eye(4)
id_2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
#slicing and memory allocation in ndarrays 
this_arr=np.random.randint(25, size=(3,4))
#slice a 2*2 matrix
this_slice=this_arr[1:3,2:5]
#slice an array to an independent memory location
new_arr=np.array(this_arr[1:3,2:5])
print(new_arr)
print(this_slice)

[[16 14]
 [16  0]]
[[16 14]
 [16  0]]


In [25]:
#upcast in numpy
x=np.array([[1,2,4,3]])
y=np.array([[0.1,0.2,0.4,0.3]],dtype=np.float64)
print(x+y)
print(x-y)

[[1.1 2.2 4.4 3.3]]
[[0.9 1.8 3.6 2.7]]


In [26]:
#squareroots of an element
print(np.sqrt(x))

[[1.         1.41421356 2.         1.73205081]]


In [30]:
#sum over rows
sor=np.random.randint(10,size=[4,5])
print(sor)
print(np.sum(sor,axis=0))

[[3 5 6 2 1]
 [6 3 0 2 1]
 [5 4 4 4 6]
 [5 7 4 5 7]]
[19 19 14 13 15]


In [31]:
#sum over cols
print(np.sum(sor,axis=1))

[17 12 23 28]


In [34]:
#product of twomatrices
print(x * y)

[[0.1 0.4 1.6 0.9]]
